# Generated by Django 2.1 on 2018-08-10 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_points',
            field=models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(60)]),
        ),
    ]
