# Generated by Django 2.1 on 2018-08-10 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20180810_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizinstance',
            old_name='quiz',
            new_name='newspaper_quiz',
        ),
        migrations.RemoveField(
            model_name='quizinstance',
            name='completed_date',
        ),
        migrations.AlterField(
            model_name='newspaperquiz',
            name='newspaper',
            field=models.ForeignKey(help_text='Avisen', on_delete=django.db.models.deletion.CASCADE, to='quiz.Newspaper'),
        ),
    ]
