# Generated by Django 2.1 on 2018-08-10 13:48

import django.core.validators
from django.db import migrations, models
import quiz.models
from django.core.validators import MaxValueValidator


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quizinstance_completed_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizinstance',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizer'},
        ),
        migrations.AddField(
            model_name='quizinstance',
            name='scored_points',
            field=models.IntegerField(default=0, validators=[
                                      MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='name',
            field=models.CharField(
                help_text='Navnet på avisen', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newspaperquiz',
            name='max_points',
            field=models.IntegerField(default=20, help_text='Øverste poenggrense', validators=[
                                      django.core.validators.MaxValueValidator(60)]),
        ),
    ]
