# Generated by Django 2.1 on 2018-08-10 13:59

import django.core.validators
from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20180810_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizinstance',
            name='scored_points',
            field=models.IntegerField(default=0),
        ),
    ]
