# Generated by Django 2.1 on 2018-08-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20180810_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspaperquiz',
            old_name='max_points',
            new_name='max_score',
        ),
        migrations.RenameField(
            model_name='quizinstance',
            old_name='scored_points',
            new_name='score',
        ),
    ]
